---
name: PyInstaller Build

on:
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:

  build-windows:
    strategy:
      matrix:
        architecture:
          - x86
          - x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8 (${{ matrix.architecture }})
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows executable
        run: >
          pyinstaller --clean --onefile --version-file file_version_info.txt -n
          sk-api-${{ matrix.architecture }} sk_chat.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sk-api-windows-${{ matrix.architecture }}
          path: dist/sk-api-${{ matrix.architecture }}.exe
